name: jammerz
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+1
  firebase_auth: ^0.11.1+3
  firebase_database: ^3.0.7
  cloud_firestore: ^0.12.9+5
  firebase_storage: ^3.0.6
  uuid: ^2.0.2
  image: ^2.1.4
  animator: ^1.0.0+1
  path_provider: ^1.3.0
  firebase_messaging: ^5.1.6
  timeago: ^2.0.20
  cached_network_image: ^1.1.1
  circular_profile_avatar: ^1.0.2
  json_serializable: ^3.2.2
  flutter_icons: ^1.0.0
  flutter_svg: ^0.14.2
  flutter_form_builder: ^3.6.1
  provider: ^3.1.0
  line_icons: ^0.2.0
  rflutter_alert: ^1.0.3
  image_cropper: ^1.1.0
  image_picker: ^0.6.1+7
  dots_indicator: ^1.0.0
  flappy_search_bar: ^1.4.1
  flutter_keyboard_visibility: ^0.7.0
  flutter_swiper: ^1.1.6
  pk_skeleton: ^0.0.2
  geoflutterfire: ^2.0.3+5
  location: ^2.3.5
  geocoder: ^0.2.1
  geolocator: ^5.1.4+2
  google_maps_flutter: ^0.5.21+8
  search_map_place: ^0.1.0+2
  video_player: ^0.10.2+5
  achievement_view: ^0.2.0
  file_picker: ^1.4.3+1
  mime: ^0.9.6+3
  firestore_ui: ^1.7.2

  # flutter_facebook_login: ^1.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/facebook.png
    - assets/images/user-placeholder.png
    - assets/images/search.svg
    - assets/images/concert.jpg
    - assets/images/silhouette.jpg
    - assets/images/musicians.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: InstrumentIcons
      fonts:
        - asset: assets/fonts/InstrumentIcons.ttf
          weight: 400
    - family: GenreIcons
      fonts:
        - asset: assets/fonts/GenreIcons.ttf
          weight: 600
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 600

    - family: Muli
      fonts:
        - asset: assets/fonts/Muli/Muli-Regular.ttf
          weight: 400
        - asset: assets/fonts/Muli/Muli-Bold.ttf
          weight: 600
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oswald/Oswald-Medium.ttf
          weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
