/// Flutter icons GenreIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GenreIcons
///      fonts:
///       - asset: fonts/GenreIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GenreIcons {
  GenreIcons._();

  static const _kFontFam = 'GenreIcons';

  static const IconData r_b = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData metal = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData bluegrass = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData punk = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData classic = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData ska = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData pop = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData alternative = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData arab = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData classical = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData jazz = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData rap = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData reggae = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData country = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData latin = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData electronic = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData funk = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData choir = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData blues = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData christian = const IconData(0xe813, fontFamily: _kFontFam);
}
