/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class InstrumentIcons {
  InstrumentIcons._();

  static const _kFontFam = 'InstrumentIcons';

  static const IconData accordion =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData acoustic_guitar =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData amp = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData amplificator =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData banjo = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData bass_guitar =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData chimes = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData conga = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData contrabass =
      const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData cymbals = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData domra = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData drum_set =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData drum = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData drumsticks =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData dual_guitar =
      const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData electric_guitar_1 =
      const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData electric_guitar_2 =
      const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData electric_guitar_3 =
      const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData electric_guitar =
      const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData fluglehorn =
      const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData flute = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData fork = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData guitar_1 =
      const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData guitar = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData harmonica =
      const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData harp = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData hfner_5001_bass_guitar =
      const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData maracas = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData hi_hat = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData metronome =
      const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData music_stand =
      const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData musical_notes =
      const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData pedal_for_guitar =
      const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData pianino = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData piano = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData saxophone =
      const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData score = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData synthetiser =
      const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData tam_tam = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData tambourine =
      const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData timbrel = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData triangle =
      const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData trombone =
      const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData trommel = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData trumpet = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData ukelele = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData violin = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData violoncello =
      const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData voltorna =
      const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData xylophone =
      const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData turntable =
      const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData hand = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData mandolin =
      const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData microphone =
      const IconData(0xe835, fontFamily: _kFontFam);
}
